import funcForm from "./modul/ajaxForm";
import funcLinks from "./modul/anchor__link";
import funcBtn from "./modul/arrowButton";
import funcBtnNavbar from "./modul/btn__navbar";
import btnFuncTop from "./modul/btnTop";
import navActive from "./modul/navActive";
import navFixed from "./modul/navFixed";
import funcValidForm from "./modul/validForm";
funcForm();
funcLinks();
funcBtn();
funcBtnNavbar();
btnFuncTop();
navActive();
navFixed();
funcValidForm();
